backend:
  name: gitlab
  repo: Kodvet/sektionshemsidan # Path to your GitLab repository
  auth_type: pkce # Required for implicit grant
  app_id: c62f906a3083fdd3ee1aa816a0a438ccb1119ca6c6dae4527b8a11139399c452 # Application ID from your GitLab settings
  api_root: https://gitlab.liu.se/api/v4
  base_url: https://gitlab.liu.se/
  auth_endpoint: oauth/authorize
  branch: static-CMS

local_backend: false

media_folder: "static/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit

  - name: 'medlemmar'
    label: 'Medlemmar'
    label_singular: 'Medlem'
    folder: 'src/pages/sektionen/styrelsemedlemmar'
    create: true
    fields:
    - { label: 'Namn', name: 'namn', widget: 'string'}
    - { label: 'Post', name: 'post', widget: 'string'}
    - { label: 'Kogvet mail', name: 'kontakt', widget: 'string'}
    - { label: 'Bild', name: 'bild', widget: 'image'}