backend:
  name: gitlab
  repo: Kodvet/sektionshemsidan # Path to your GitLab repository
  auth_type: pkce
  app_id: 1fd03c5ff044c3a3abff03589e28d67bce9b3ccb0ff2ad39764fd46e4dbf0c38 # Application ID from your GitLab settings
  api_root: https://gitlab.liu.se/api/v4
  base_url: https://gitlab.liu.se/
  auth_endpoint: oauth/authorize
  branch: main

local_backend: false
logo_url: https://sektionshemsidan.netlify.app/images/Sektionslogga 1.png
display_url: https://sektionshemsidan.netlify.app
media_folder: "/static/images"
public_folder: "/images"
locale: sv
slug:
  encoding: "ascii"
  clean_accents: true

collections: # A list of collections the CMS should be able to edit
  
  - name: nyheter
    label: Nyheter
    label_singular: nyhet
    folder: src/data/nyheter
    create: true
    slug: '{{slug}}'
    icon: newspaper
    view_filters:
      - label: Utkast
        field: draft
        pattern: 'true'
      - label: Publicerade
        field: draft
        pattern: 'false'
    view_groups:
      - label: Månad publicerad
        field: date
        pattern: '[a-zA-Z]+'
      - label: Författare
        field: author
    editor:
      preview: false
    fields:
     - {label: Utkast?, name: draft, widget: boolean}
     - {label: Författare, name: author, widget: relation, collection: medlemmar, value_field: 'namn', search_fields: ['namn', 'post', 'utskott']}
     - {label: Rubrik, name: title, widget: string, required: true}
     - {label: Datum, name: date, widget: datetime, date_format: dd-MM-yyyy, time_format: false, format: "dd-MMMM-yyyy"} 
     - {label: Omslagsbild, name: img, widget: image, required: false}
     - {label: Utdrag, name: excerpt, widget: text, required: true, 
        hint: "Detta är det som står på startsidans nyhetsflöden. 
                Du behöver inte komma på nåt speciellt.
                Förslagsvis kan du copy pastea 3 första meningarna från inlägget"}
     - {label: Inlägget, name: body, widget: markdown, required: true}

  - name: 'medlemmar'
    identifier_field: namn
    label: 'Medlemmar'
    label_singular: 'Medlem'
    folder: 'src/data/medlemmar'
    icon: usergroup
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    view_groups:
      - label: 'Utskott'
        field: utskott
    fields:
    - { label: 'Namn', name: 'namn', widget: 'string'}
    - { labek: 'Utskott', name: 'utskott', widget: relation, collection: utskott, value_field: 'title', search_fields: ['title'] }
    - { label: 'Post', name: 'post', widget: 'string'}
    - { label: 'Kogvet mail', name: 'kontakt', widget: 'string'}
    - { label: 'Bild', name: 'bild', widget: 'image', media_library: {choose_url: true}}
    - { label: 'Om mig', name: 'body', widget: 'markdown', required: false,
        hint: '(Ni får själv velja om detta ska vara obligatoriskt) 
                Skriv lite om dig själv, varförd du valde kogvet, linköping. 
                Varför du sökte till din post. Eller bara något roligt, fan vet jag'}

  - name: 'utskott'
    label: 'Utskott'
    folder: 'src/data/utskott'
    icon: userrectangle
    slug: '{{slug}}'
    create: true
    editor:
      sortable_fields: [title]
    fields:
      - { label: 'Namn', name: 'title', widget: 'string', required: true,
          hint: 'Namnet här blir tillgängligt i listan av utskott som en "medlem" kan tillsättas' }
      - { label: 'Innehåll', name: 'body', widget: 'markdown', 
          hint: 'Detta är det som kommer stå i mitten-rutan på sidan'}
  
  # - label: Sidor
  #   label_singular: sida
  #   name: sidor
  #   icon: sitemap
  #   folder: src/pages/
  #   summary: '{{dirname}}'
  #   description: Här är (för närvarande) alla sidor förutom de som innehåller speciella komponenter (såsom de för utskotten).
  #   nested:
  #     depth: 4
  #   fields: 
  #     - { label: 'Mall', name: 'layout', widget: 'select', options: [
  #         { label: Basic, value: ../../layouts/Basic.astro },
  #       ]}
  #     - { label: Innehåll, name: body, widget: markdown, hint: 'Detta är det som kommer stå i mitten-rutan på sidan'}
  #     - {label: Title, name: title, widget: string, hint: Detta är namnet som dyker upp i entries-listan, samt utgör mallen för filnamnet}
  #   meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  #   create: true
  
  - name: config
    label: Inställningar
    # extensions: json
    icon: cog
    editor:
      preview: false
    files:
      - label: Färgschema
        name: css-colors
        file: src/CSSTheme.json
        fields:
          - label: Färger
            name: :root
            widget: object
            fields:
              - {label: Bakgrund, name: --background-color, widget: color, allow_input: true}
              - {label: Navbar färg, name: --navbar-bg, widget: color, allow_input: true}
              - {label: Navbar dropdown färg, name: --navbar-dropdown-bg, widget: color, allow_input: true}
              - {label: Navbar aktiv dropdown färg, name: --navbar-active-dropdown-bg, widget: color, allow_input: true}
              - {label: Sidfot-färg, name: --footer-bg, widget: color, allow_input: true}
      
      - label: Navbar config
        name: navbarConfig
        file: src/navbarConfig.json
        fields:
          - label: Sidor
            label_singular: Sida
            name: pages
            create: true
            widget: list
            collapsed: true
            fields:
              - {label: Namn, name: btnName, widget: string}
              - {label: url, name: url, widget: string}
              - {label: Är genomskinlig?, name: isOpaque, widget: boolean, default: true}
              - label: Underordnade sidor
                label_singular: Sida
                name: childPages
                widget: list
                create: true
                collapsed: true
                required: false
                fields:
                  - {label: Namn, name: btnName, widget: string}
                  - {label: url, name: url, widget: string} 
                  - {label: Är genomskinlig?, name: isOpaque, widget: boolean, default: true}

  - name: kod
    label: Kod
    format: frontmatter
    icon: code
    description: Här finns lite rå kod. Tror inte ni har så många anledningar till att ändra här - om ni vill göra det kan ni lika gärna koda direkt på git, eller kontakta kodvet. Men det finns här iallafall
    files: 
      - name: css
        label: Global CSS
        file: src/globalStyles.css
        fields:
          - {name: body, label: kod, widget: code, default_language: css, allow_language_selection: true, code_mirror_config: { language: CSS, theme: 'material' }, output_code_only: true, hint: Dessa styles appliceras för hela sidan. Exempelvis kan det ju hända att ni skulle vilja justera nyanser av vårt standar-färgschema.}
